server:
  port: 8080

grpc:
  client:
    nickname-service:
      address: 'static://nickname-service:9093'
      negotiation-type: plaintext
    personal-transaction-service:
      address: 'static://personal-transaction-service:7095'
      negotiation-type: plaintext
    personal-user-service:
      address: 'static://personal-user-service:7094'
      negotiation-type: plaintext