server:
  port: 8080

grpc:
  client:
    nickname-service:
      address: 'static://localhost:9093'
      negotiation-type: plaintext
    personal-transaction-service:
      address: 'static://localhost:7095'
      negotiation-type: plaintext
    personal-user-service:
      address: 'static://localhost:7094'
      negotiation-type: plaintext

#Need to add this to ensure gateway don't use db for a while
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration