server:
  port: 3501

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: leng
    password: 20122002
    driverClassName: org.postgresql.Driver

grpc:
  server:
    port: 7094
