server:
  port: 3501

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

grpc:
  server:
    port: 7094
