server:
  port: 3502

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microbanking
    username: leng
    password: 20122002
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

grpc:
  server:
    port: 7095
